title: Jspha
baseURL: https://jspha.com/
languageCode: en-us
theme: ghost

googleAnalytics: UA-82055587-1

params:
  description: >
    Writing on technology, storytelling, leadership, photography. Candid
    alter-ego of [Simplicial](https://simplicial.io).
  logo: /logo.png
  subscribe: false # true if subscribe form shows
  social:
    twitter: https://twitter.com/sdbo/
    github: https://github.com/tel/
    instagram: https://www.instagram.com/sdbo/
    linkedin: https://www.linkedin.com/in/abrahamsonj/
  twitter_url: https://twitter.com/sdbo
  themeColor: theme-base-0b
  layoutReverse: true

menus:
  # Add menu items here, {name: ..., url: ...}
  main: []
